### ISSUE TITLE
Farben in der Hauptnavigation

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#1]
Hallo,

der Kontrast der Schrift in der aufklappbaren Hauptnavigation ist zu gering zum Grün des Hintergrunds. Die Schrift sollte heller sein. Können Sie das bitte ändern?

![nat-screenshot1](https://cloud.githubusercontent.com/assets/8234890/7451442/fbab19e8-f250-11e4-8b92-2c7dca968ae9.png)

**Comment by cibsell** [comment]
Ebenso: in der Sidebar sind die grünen Balken des Individuellen Menüs störend.

**Comment by cibsell** [comment]
Im Platzhalter-Bild (Siegel) sind grüne Flecken. Ist  das Bild transparent, so dass man den grünen Hintergrund durchsieht? Kann man den Hintergrund / Rahmen abstellen?

**Comment by cibsell** [comment]
Bei Accordion-Menüs ist der Hintergrund ebenfalls zu dunkel.

**Comment by xwolfde** [comment]
Bitte genauer! Ohne konkrete Vorschläge (Farbcode) ändere ich nichts.

**Comment by xwolfde** [comment]
Das Siegel (https://github.com/RRZE-Webteam/FAU-Natfak/blob/master/img/siegel-natfak.png) ist nicht flecikig, das ist der Balken des Hintergrunds. Dieser Balken ist NICHT durchgängig, sondern hat Übergänge via CSS. Das wurde ebenfalls so abgenommen.

**Comment by cibsell** [comment]
Im obigen Bild ist das Siegel nicht grün, sondern schwarz. Das ist das Platzhalter-Bild bei News-Meldungen. Hier ein besserer Screenshot:

![platzhalter-siegel-news](https://cloud.githubusercontent.com/assets/8234890/7509800/9b9b463a-f495-11e4-97fb-ad364511babb.png)

Ebenso ist der grüne Hintergrund hinter den News-Bildern störend. Dieser sollte weiß sein und nicht grün (bzw. in den anderen Themes ist er auch in Fakultätsfarben). 

Screenshot:

![news-bild-hintergrund](https://cloud.githubusercontent.com/assets/8234890/7509818/cf3e117a-f495-11e4-9caf-1d60ef94875c.png)

**Comment by xwolfde** [comment]
Bäh, da hast recht, wo kommt denn das her :(
Aber an der Stelle wäre sowieso zu überlegen, ob wir nicht mal ein anderes Platzhalterbild machen. Hast du ein Vorschlag?

Das die Bilder ein "Passpartout" haben war/ist heftig von der ZUV erstrittener Teil des Designs. Und das Design wurde so abgenommen. 
Die Rahmenfarben ist eine der Basisfarben des Themes. Alle Basisfarben ergeben sich aus der festgelegten Fakultätsfarbe die fix ist. (siehe Link in der variables-Datei zu dem Generator der Palette)

**Comment by cibsell** [comment]
Mangels eines spontanen Vorschlags würde ich es erst einmal bei diesem Siegel-Platzhalter belassen.

Beim NAT-Theme holt sich das Theme das Platzhalterbild übrigens aus dem Phil-Theme: .../wp-content/themes/FAU-Philfak-master/img/default-postthumb.png Ich nehme an, das PNG ist transparent, wenn dieses mit weißem Hintergrund gestaltet würde, würden sich die Flecken erübrigen. im Phil-Theme sind die Flecken "gelb". Daher wird wohl das "Passpartout" durchscheinen.

Prinzipiell finde ich das Passpartout nicht so schlimm, aber bei den Fakultäts-Themes wirken sie sehr bunt und machen die Startseite unruhig. Auf der FAU-Seite sind die Passpartouts auch nicht dunkelblau, sondern hellgrau. Könnte man das für die Fakultäts-Themes nicht genauso machen?

**Comment by xwolfde** [comment]
Hm... Ich kann schon und ganz schlecht fände ich es auch nicht. Nur genau das ist halt etwas, was tatsächlich so aus den Agenturcode kommt. 
Und wenn wir das machen, muss es für alle gelten - denn es wäre doof, wenn es bei euch grau wäer, bei der RW dann aber doch wieder bunt...

**Comment by xwolfde** [comment]
Also: Philfak ist ebenfalls dafür, Natfak vertrittst du, bei FAU ists eh schon so.  Bei Tech ists eh auch grau -pardon-silber,  wir machen das so: Passpartout wird hellgrau.

**Comment by cibsell** [comment]
Toll!

**Comment by xwolfde** [comment]
Noch nicht auf CMS, aber hier im GitHub: Farbe des Passpartous ist nun das Standardgrau. 
Ausserdem hab ich den Mediaquery nochmal modifiziert. Leider funktionierte das Hamburger Menu garnicht. Jetzt als provisorum sind wieder alle Menüs zugänglich ohne Hamburger. Ist zwar doof zu bedienen, aber jetzt lässt es sich überhaupt bedienen (das ging vorher nicht).

**Comment by xwolfde** [comment]
Inzwischen angepasst
