### ISSUE TITLE
2x Sidebar?

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#11]
Guten Morgen, 

bei mir (NAT-Testseite auf der RRZE-Instanz) erscheint im Theme bei allen Templates zweimal die Möglichkeit etwas in einer Sidebar einzugeben. Die erste Sidebar ist aber offensichtlich nicht die Sidebar rechts, sondern erscheint unterhalb des normalen Contents. Die zweite Sidebar ist optisch fast identisch mit der ersten Sidebar-Möglichkeit, nur dass hier das Menü "Auswahl Ansprechpartner" vor dem Linkblock kommt. Die gleiche Bezeichnung ist sehr verwirrend und missverständlich und soll sicher nicht so sein, oder?

**Comment by xwolfde** [comment]
Ich stehe gerade auf den Schlauch. Kannst du mal ein Screenshot machen?

**Comment by cibsell** [comment]
![ss1](https://cloud.githubusercontent.com/assets/8234890/9927135/3770e012-5d1c-11e5-90c3-dc9cf20031b7.png)
![ss2](https://cloud.githubusercontent.com/assets/8234890/9927133/3762150a-5d1c-11e5-8041-9c0a86334dd3.png)
![ss3](https://cloud.githubusercontent.com/assets/8234890/9927134/3762088a-5d1c-11e5-931c-192a3e925dbd.png)

**Comment by xwolfde** [comment]
Du hattest das Plugin RRZE Page Sidebar aktiviert. Dieses macht die Sidebars auch. Es ist gedacht für *andere* Themes, die diese Sidebar nicht haben aber bekommen wollen. :)

**Comment by cibsell** [comment]
Ok, alles klar, danke!
