### ISSUE TITLE
Anzeige Artikel (single): Widget Kategorien mit Hierarchien

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Natfak#12]
Die Listelemente im Widget bei der Anzeige eines Artikels sind flach:
Unterkategorien werden nicht eingerückt.

**Comment by steffigebel** [comment]
Verstehe ich nicht. Kannst du ein Beispiel als Screenshot anführen?

**Comment by xwolfde** [comment]
Im nächsten Update erledigt-
![screenshot-widget-categories-hierarchy](https://cloud.githubusercontent.com/assets/1070669/13354068/d31e6916-dc98-11e5-823d-24e5513bdfa9.jpg)
