### ISSUE TITLE
Ausgabe Plugin FAU_Person Format compactindex

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Natfak#16]
Die Ausgabe  eines Personenindexes über das Format Compactindex soll optisch zur Verfügung gstellt werden.
Vgl:
https://github.com/RRZE-Webteam/fau-person/issues/60
https://github.com/RRZE-Webteam/fau-person/issues/109

**Comment by cibsell** [comment]
In dem Zusammenhang wäre auch wünschenswert, wenn der Name der Person nicht in H2 - Überschrift erscheint, sondern z. B. in H3 oder H4, vergl. https://test.nat.fau.de/fakultaet/dekanat/ . Wenn man mehrere Kontakte untereinander einfügt, dann muss man mehrere H2-Überschriften im Content definieren, damit es gut aussieht.

**Comment by cibsell** [comment]
Kontaktdaten müssen über die gesamte Breite des Content-Bereichs gehen. 

Beispiel unschöne Formatierung:
![kontakte1](https://cloud.githubusercontent.com/assets/8234890/11113121/508e0532-891a-11e5-92bf-351c61c4d21e.jpg)

Statt h2 sollte h3 oder h4 als Namen/Titel-Überschrift stehen:
![kontakte2](https://cloud.githubusercontent.com/assets/8234890/11113122/50acdcdc-891a-11e5-8d64-59726f98c663.jpg)
