### ISSUE TITLE
Zeilenumbruch im Portalmenü einfügen

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#17]
Hallo,

ich habe ein Portalmenü erstellt für eine Übersichtsseite Lehrstühle am Department: 

![portalmenue-zeilenumbruch1](https://cloud.githubusercontent.com/assets/8234890/11088960/78eb0458-8866-11e5-8fc2-45494b59ba03.jpg)

Es wäre schön, wenn ich einen Zeilenumbruch zwischen Lehrstuhlname und Professorenname eingeben könnte. Leider wird der Zeilenumbruch ( < br / > ) automatisch wieder rausgelöscht, wenn ich ihn eingebe. Auf meiner alten Testseite (chem.nat.fau.de) hatte es funktioniert, da sah das Menü viel übersichtlicher aus:

![portalmenue-zeilenumbruch2](https://cloud.githubusercontent.com/assets/8234890/11089093/48de494a-8867-11e5-8a92-a7966aa93d3a.jpg)

Gibt es eine Möglichkeit hier einen Zeilenumbruch einzufügen?

**Comment by AstridSemm** [comment]
Das ist jetzt dumm, bei mir funktioniert das nämlich. Das sehen wir uns die Tage mal dort an, denke ich.

![bildschirmfoto 2015-11-11 um 13 50 20](https://cloud.githubusercontent.com/assets/11296947/11091501/3ac7bb66-887b-11e5-9d42-6287b8c0070c.png)
![bildschirmfoto 2015-11-11 um 13 49 58](https://cloud.githubusercontent.com/assets/11296947/11091502/3c35c9a2-887b-11e5-9c74-fc89623a2e84.png)

**Comment by cibsell** [comment]
Bei mir geht es nicht...

Siehe auch https://test.nat.fau.de/studium/studiengaenge/master/ , da wäre es schön, wenn vor (MSc.) ein Zeilenumbruch wäre, damit die Menüzeilen auf einer Höhe sind.

**Comment by cibsell** [comment]
Gibt es da schon eine Lösung?

**Comment by steffigebel** [comment]
https://test.nat.fau.de/studium/studiengaenge/master/ Hier sieht man es auch nochmal ganz deutlich. 
@xwolfde bitte einmal dazu Stellung beziehen! Danke!

**Comment by xwolfde** [comment]
Ich sehe keine praktikable Lösungsmöglichkeit, die nicht wiederum andere Probleme verursachen würde:

Eine Lösung, die das ganze korrekt beheben würde, müsste dahin gehen, daß man für die verlinkten Seiten wiederum Neben- oder Untertitel in einem Extraeingabefeld eingeben müsste.
Ausserdem haben wir hier auch noch einen semantischen Break und nicht nur einen optischen. Diese müsste auch im Markup berücksichtigt werden.

Dieses Feld würde allen Nutzern zur Verfügung stehen. Auch solchen die es nicht brauchen und die davon irritiert wären. Das wäre die Mehrzahl alle User.
Dies würde wiederum unseren Beratungsaufwand erhöhen und es würde nicht compatibel zu anderen Themes sein, die ja so ein Eingabefeld nicht kennen und daher nicht berücksichtigen werden.

Also:
Wenig Vorteile - Nutzung und Bedarf jetzt zum ersten mal bei einer Einrichtung.
Dagegen Aufwand der Programmierung, Wartung und der Betreuung.

Der Wunsch ist berechtigt. Aber aus den genannten Gründen und der Abwägung der Vor- und Nachteile sehe ich momentan keine Chance dafür.

**Comment by AstridSemm** [comment]
Was machen wir dann jetzt damit? Mit wontfix schließen oder noch offen lassen für zukünftige Bearbeitung?

**Comment by xwolfde** [comment]
Wie oben dargelegt, sehe ich keine praktikable Lösung. Also Wontfix.
Es sei denn jemand anders schlägt da was vor?
