### ISSUE TITLE
Veranstaltungs-Defaultbild wird nicht eingebunden

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Natfak#18]
![bildschirmfoto 2015-11-17 um 15 07 04](https://cloud.githubusercontent.com/assets/11868989/11213622/3463683a-8d3d-11e5-8723-ed216aaaa0bc.png)
Wenn kein Bild ausgewählt ist (Beitrag/Top Event), dann nimmt er nicht das default Bild.

**Comment by xwolfde** [comment]
Bei mir geht es... Mglw. wurde bei Import/Export der Einträge in eine andere WP-Instanz das Bild nicht mit übernommen?
