### ISSUE TITLE
Inhaltsseite mit Navi

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#2]
Hallo,

wie heißt das Menü, auf das die "Inhaltsseite mit Navi" zugreift und dieses auf der linken Seite anzeigt? Wie kann ich dort individuelle Links einfügen?

**Comment by steffigebel** [comment]
Guten Tag cibsell,

Je nachdem, wie man es benennt, so heißt das Menü. Meist ist es das Hauptmenü Header. Individuelle Links erstellt man im Design>Menü>Menü bearbeiten.

Grüße,
Steffi Gebel
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Natfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 3. Juni 2015 15:28
An: RRZE-Webteam/FAU-Natfak <FAU-Natfak@noreply.github.com<mailto:FAU-Natfak@noreply.github.com>>
Betreff: [FAU-Natfak] Inhaltsseite mit Navi (#2)


Hallo,

wie heißt das Menü, auf das die "Inhaltsseite mit Navi" zugreift und dieses auf der linken Seite anzeigt? Wie kann ich dort individuelle Links einfügen?

**Comment by steffigebel** [comment]
Hallo Frau Sell,

Sie haben Recht! Es funktioniert sichtbar nur im Header-Menü, nicht in der Nav-Bar links. Da tut sich nichts. Ich werde es als Bug vermelden scheint Theme-übergreifend zu sein.

Danke für den Hinweis!

Grüße,
Steffi Gebel
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Natfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 3. Juni 2015 15:28
An: RRZE-Webteam/FAU-Natfak <FAU-Natfak@noreply.github.com<mailto:FAU-Natfak@noreply.github.com>>
Betreff: [FAU-Natfak] Inhaltsseite mit Navi (#2)


Hallo,

wie heißt das Menü, auf das die "Inhaltsseite mit Navi" zugreift und dieses auf der linken Seite anzeigt? Wie kann ich dort individuelle Links einfügen?

**Comment by cibsell** [comment]
Danke! :)

**Comment by steffigebel** [comment]
Bug hier dokumentiert. Gilt auch hier im NATFak-Theme https://github.com/RRZE-Webteam/FAU-Philfak/issues/43

**Comment by xwolfde** [comment]
Nein. Dort wird eben kein Menu verwendet.
Das "Menu" bildet sich autromatsich aus allen Seiten die in dier zugehörigen Seitenhierrarchie sind.

vgl. auch 
https://github.com/RRZE-Webteam/FAU-Philfak/issues/43
und insbesondere hier:
https://github.com/RRZE-Webteam/FAU-Theme/issues/212

Das ganze kam so von der ZUV-Seite. Ich finde es auch blöd. Ist aber jetzt so. Ist kein Bug ist aber ungeschickte Umsetzung.

**Comment by cibsell** [comment]
Für uns als Fakultät und auch für unsere Departments wäre die Umsetzung als individuelles Menü aber sehr wichtig, denn es wird oft auf ZUV-Seiten oder z. B. auch auf andere externe Seiten (Forschungskooperationen) etc. verlinkt.

**Comment by xwolfde** [comment]
Ich hab hier dazu was geschrieben:
https://github.com/RRZE-Webteam/FAU-Philfak/issues/43

Individuelle Menüs kann man ja auf Portalseiten machen. Die Inhaltsseite mit Nav ist nur für "normale" Seiten innerhalb der eigenen Seitenhierarchie vorgesehen.
Externe Links in einem solchen Menü sollte man davon unabhängig garnicht machen, weil das die einheitliche Menüführung durchbricht. Dafür sind dann die Portalmenüs bzw. Imagemenus gedacht.

Sorry, so ist das "Design" des Themes nun mal.
