### ISSUE TITLE
Die per default auszuwählenden Logos der Fakultäten 

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Natfak#20]
sind nicht hochauflösend und sehen bei genauem Betrachten sehr verpixelt aus

**Comment by xwolfde** [comment]
Die sind bereits ein Kompromiss. Da können wir leider momentan nichts drehen. ggf. wird es bei den Reparaturarbeiten zu den RWD nochmal dran kommen. Momentan jedoch nicht.
