### ISSUE TITLE
Sprachbutton verschoben

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#22]
Sowohl im IE, Firefox als auch Chrome ist der Sprachbutton im NAT-Theme ein paar Pixel nach unten verschoben im Vergleich zum Suchbutton. Bitte auf eine einheitliche Höhe bringen. Danke!

![sprachbutton](https://cloud.githubusercontent.com/assets/8234890/12349744/5023770a-bb72-11e5-8315-4abb62d57428.jpg)

**Comment by cibsell** [comment]
Bei www.rw.fau.de sieht man die Verschiebung auch, nur bei fau.de sind beide Buttons auf gleicher Höhe.

**Comment by xwolfde** [comment]
WTF?!

.mlp_language_box   hat ein margin-top:10 - muss 5px sein.
Wo kommt das auf einmal her?.. Strange.
Korrektur dauert bis zum nächsten Themeupdate.

**Comment by xwolfde** [comment]
in der nächsten Version drin
