### ISSUE TITLE
Linklisten Sidebar fehlerhaft

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#23]
Ich möchte über die Sidebar zwei Links einfügen. Das mache ich über den Linkblock und wähle mir zwei Links über "Wähle Links" aus. Dabei treten zwei Probleme auf:

1. Der "Titel" des Links wird gelöscht, wenn ich den Link ausgewählt und auf "Link auswählen" geklickt habe.

2. Jeder bereits vorhandene Link in der Linkliste wird mit der URL des neuesten ausgewählten Links überschrieben.

**Comment by xwolfde** [comment]
zu 1. 
Ja. Ist leider so, können wir momentan nicht ändern. Ein Case bei WP-Dev ist dazu auch offen, da die Ursachen bei einer zugrunde liegenden API liegen, die seit 4.1 keinen Title mehr liefert.
Daher wird der Titel von URLs die zur Site gehören grundsätzlich immer aus dem Seitentitel der verlinkten Seite geholt.
Derzeit (seit ein paar Monaten) können wir da nichts tun. Die Funktionalität ist da so wie sie ist.

zu 2. 
Bitte genauer. Am besten mit URL zum Nachvollziehen.

**Comment by cibsell** [comment]
Zu 2.: 
Ich will über die Sidebar zwei Links anlegen, die zu weiteren Informationen führen, z. B. unter https://test.nat.fau.de/schule/lehrer/ . Der erste lässt sich problemlos anlegen. Doch wenn ich die URL des zweiten Links mit "Link auswählen" anklicke, dann legt Wordpress nicht nur den zweiten Link an, sondern überschreibt beim ersten Link die zuvor angelegte andere URL mit der URL des zweiten Links.

**Comment by steffigebel** [comment]
Dann einfach manuell einfügen, das klappt, bei mir jedenfalls.
Wählen Sie bei „Wähle Link“ eine bestehende Seite aus? Sonst wäre der Schritt im Gegensatz zu dem manuellen einfügen in die Zeilen auf der Seite sowieso mehr Aufwand ;-)

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Natfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 21. Januar 2016 09:35
An: RRZE-Webteam/FAU-Natfak <FAU-Natfak@noreply.github.com<mailto:FAU-Natfak@noreply.github.com>>
Betreff: Re: [FAU-Natfak] Linklisten Sidebar fehlerhaft (#23)


Zu 2.:
Ich will über die Sidebar zwei Links anlegen, die zu weiteren Informationen führen, z. B. unter https://test.nat.fau.de/schule/lehrer/ . Der erste lässt sich problemlos anlegen. Doch wenn ich die URL des zweiten Links mit "Link auswählen" anklicke, dann legt Wordpress nicht nur den zweiten Link an, sondern überschreibt beim ersten Link die zuvor angelegte andere URL mit der URL des zweiten Links.

**Comment by xwolfde** [comment]
F*ck!
Scheiss JS-Geraffel an der Stelle.

**Comment by xwolfde** [comment]
Fixed im nächsten update
