### ISSUE TITLE
Schriftgröße in Tabellen

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#24]
Hallo,

mir werden innerhalb einer Tabelle unterschiedliche Schriftgrößen angezeigt, auch wenn die Schrift nicht formatiert ist, siehe https://chemie.cms.rrze.uni-erlangen.de/arbeitskreis-schatz/curriculum-vitae/ 

Der Punkt "Gastwissenschaftleraufenthalte -> Stipendiat" ist größer als der erste Punkt.

**Comment by AstridSemm** [comment]
Hallo Christiane,
das passiert, wenn man im WYSIWYG-Editor einen Absatz eingibt (also 2x Return-Taste drücken). Der WYSIWYG-Editor fügt dann im Hintergrund ein <p>-Tag ein, was zu der größeren Schrift führt.
Workaround: Absätze grundsätzlich im Texteditor eingeben (sorry, ich weiß da gerade nichts Besseres).

**Comment by AstridSemm** [comment]
*grrrr* Es ist ein &lt;p&gt;-Tag. Meine Güte!

**Comment by xwolfde** [comment]
Wird nach dem nächsten Update genauso aussehen wie normaler Nicht-Absatztext.
