### ISSUE TITLE
Fehlerhafter Upload

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#25]
Ich erhalte oft eine Fehlermeldung, wenn ich Medien hochlade. Es wird nur der Fehler ausgegeben "HTTP error." Gerade eben passiert z. B. von 37 hochgeladenen Dateien hatten 4 diese Fehlermeldung. Es geschieht unabhängig vom Format, egal ob JPG oder PDF. In der Medial Library Übersicht werden die Dateien nicht angezeigt, aber wenn ich danach suche, sind sie vorhanden.

**Comment by xwolfde** [comment]
Bitte sowas nicht hier melden, sondern via Mail an webmaster@   . Ansonsten geht das schlicht unter.
Das Problem ist bekannt und liegt ausserhalb der Themes; Es handelt sich um ein Problem mit PHP-Libraries auf dem Server, die ein Cache schneller voll machen als das dieser automatisch gelöscht wird.

Workaournd ist: Nochmal versuchen.
