### ISSUE TITLE
Bühnenbild - Bildunterschrift

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#28]
Die Bildunterschrift beim Bühnenbild ist die gleiche, die auch beim Beitragsbild angezeigt wird. Nun wird beim Beitragsbild im Beitrag aber oft erklärender Text zur Grafik o.ä. dazu geschrieben. Der Text im Bühnenbild soll aber nicht zu lang werden, da er sonst das Bühnenbild unschön verdeckt bzw. über die Pfeiltasten geht.

Siehe z. B. https://www.nat.fau.de/ beim Bühnenbild zum Beitrag "Ein Reisender aus einer fernen Galaxie" oder "Das Zentrum der Milchstraße". Dort ragt die Bildunterschrift in die Pfeiltasten hinein. Ich musste auch den Titel des Beitrags kürzen, da sich andernfalls die Schrift überlagern würde.

Gibt es eine Einstellung oder Möglichkeit, dass man für das Bühnenbild extra eine Bildunterschrift eingeben kann, die nur beim Bühnenbild verwendet wird? Es gibt zwar den Punkt "Ersetze Bildbeschreibung" unter Beitragsoptionen, aber wenn ich die Option verwende, dann ändert sich sowohl die Bildunterschrift im Bühnenbild als auch beim Beitrag selbst. Das ist aber genau das, was ich nicht möchte. Im Beitrag soll die lange Bildunterschrift erhalten bleiben.

**Comment by xwolfde** [comment]
Nein.
Im Beispiel wird der Text auch falsch verwendet. Dort gehört die Copyright Infos des Bildes rein und keine Bildbeschreibung. Alles andere ist an der Stelle falsch.

Einstellungsmöglichkeiten zu dem Amzeigetext finden sich unter Theme Options->Erweitert->Design.

**Comment by cibsell** [comment]
Erstens steht dort in der Option "Bildbeschreibung". Zweitens ändert obige Aussage nichts am Problem, dass sich bei Beitragsbild der Text der Bildbeschreibung auch ändert, wenn ich ihn beim Bühnenbild ändere.

**Comment by xwolfde** [comment]
Das ist so gewollt.
Bilder gehören an der Stelle nicht vollumfänglich erklärt sondern im umrandenden Text, wo die Bilder verwendet werden. Bei dem hero handelt sich am ein Slider, bei dem das Bild nur schmückendes Beiwerk ist. Die inhaltliche Aussage erfolgt im Titel und im Teaser. In der Bildinfo soll nur die Copyrightinfo angezeigt werden. Nur dafür wurde dies dort gemacht. Nicht für andere Texte.
Alles andere ist Fehlbedienung.

**Comment by cibsell** [comment]
Du verstehst mich offensichtlich nicht.

Aber gut. Ich löse das Problem, indem ich das gleiche Bild einfach zweimal hochlade. Ist zwar nicht Ressourcen sparend, aber offensichtlich so gewollt.

**Comment by xwolfde** [comment]
Nein, du hast das was ich als erstes geschrieben ignoriert.
Du hast selbst (denn von uns ist es das andere als Default vorgegeben) in den Theme Otions angegeben, dass das Eingabefeld "Beschreibung" Priorität erhält vor den anderen Texten.
Auswahlfeld: "Copyright-Info ermitteln"

Ändere dies zurück auf Copyright und alles ist gut.
Die Bildbeschreibung ist unabhängig davon immer gleich zu halten, denn das Bild ändert sich nicht.
