### ISSUE TITLE
Fehler im horizontalen Hauptmenü

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#3]
Habe mir gerade die neuste Version (1.7.2015) hochgeladen. Irgendetwas stimmt mit dem horizontalen Menü nicht. Der erste Menüpunkt ist weiße Schrift auf weiß, beim Hover ist der Punkt zwar zu sehen (weiße Schrift auf grün), aber es ist ein weißer Balken dazwischen, der im FAU-Theme nicht enthalten ist und vermutlich auch nicht so sein soll...

![weiss-hm1](https://cloud.githubusercontent.com/assets/8234890/8455435/ea2678fc-2004-11e5-9ac0-110effa6b26f.jpg)
![weiss-hm2](https://cloud.githubusercontent.com/assets/8234890/8455434/ea1499ac-2004-11e5-84a1-3f888dc7a817.jpg)

**Comment by xwolfde** [comment]
Hm, bei mir ist das nicht so... http://test4.wordpress.webhummel.rrze.uni-erlangen.de/ 
Hast du irgendwelche CSS-Optionen bei dem Menüeintrag gemacht?

**Comment by cibsell** [comment]
Nein, nichts...

**Comment by xwolfde** [comment]
Browser? Auflösung?

**Comment by cibsell** [comment]
Ist sowohl im Chrome (43.0.2357.130 m) als auch im Firefox (35.0.1). Auflösung 1920 x 1080.

**Comment by xwolfde** [comment]
auf einer URL, die ich erreichen kann?

**Comment by cibsell** [comment]
Ich habe Dich für die Seite freigeschaltet.

Das passiert auch mit allen anderen Menüpunkten, die Unterpunkte haben, nicht nur beim ersten in der Reihe. Möglich aber auch, dass irgendetwas falsch eingestellt ist...

**Comment by xwolfde** [comment]
Hm, damit sehe ich auch nicht das neue Theme...
Wir haben aber inzwischen auch aus der Phil Reports über sporadisch auftretene Fehler in der Optik.
Diese lassen sich nur nachvollziehen, wenn hoch und runter gescrollt wird...
Sehr schwierig...

**Comment by cibsell** [comment]
An den Plugins liegt es leider auch nicht. Das Problem besteht mit deaktivierten Plugins weiterhin.

**Comment by xwolfde** [comment]
:(

**Comment by xwolfde** [comment]
Kommst du auf meine test4 rauf und kannst du den Fehler dort auch finden?

**Comment by cibsell** [comment]
Ja... und nein...

**Comment by xwolfde** [comment]
Wäre ich doch bloß Physiker geblieben... :)

**Comment by xwolfde** [comment]
Tritt das Problem mit der neuen Version noch auf?

**Comment by cibsell** [comment]
Das Problem mit der weißen Schrift auf weißem Hintergrund ist jetzt weg. Das Problem vom 2. Screenshot existiert weiterhin, allerdings nur, wenn die Seite nach unten gescrollt wird. Wenn die Seite nicht gescrollt wird und das Hover-Menü aufgeklappt wird, dann ist kein leerer Zwischenbalken vorhanden.

**Comment by cibsell** [comment]
Habe gerade auf der NAT-Seite die neue Version vom Theme eingespielt. Da besteht das Problem mit der weißen Schrift weiterhin, nur auf der Chemie-Seite ist es weg.

**Comment by cibsell** [comment]
Habe noch einmal einen komplett neuen Webauftritt in der Multisite-Instanz angelegt mit allen aktuellen RRZE-Plugins und dem aktuellen Theme. Der Fehler tritt da auch auf.

**Comment by cibsell** [comment]
Der Fehler tritt übrigens auch auf, wenn ich das PhilFak-Theme verwende!

**Comment by xwolfde** [comment]
Wird im nächsten Update behoben sein.
testcase hier:
test8.tindu.rrze.uni-erlangen.de
