### ISSUE TITLE
Bilderrahmen Logo

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#34]
Gibt es eine Möglichkeit den voreingestellten "Bilderrahmen" bei Logos (im Content-Bereich / Fließtext) auszuschalten?

**Comment by xwolfde** [comment]
Nein.

**Comment by cibsell** [comment]
Gibt es dafür auch eine Begründung? Die Professoren hätten die Logos gerne ohne Rahmen...

**Comment by xwolfde** [comment]
Weil das Design so vorgegeben ist.
