### ISSUE TITLE
Darstellung im Safari

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#35]
Ein Kollege meint, im Safari wird die Hauptnavigation unterhalb des Logos angezeigt, egal welche Bildschirmbreite.

![unspecified](https://cloud.githubusercontent.com/assets/8234890/15651599/e0484012-2680-11e6-9ed0-9465198483da.png)

**Comment by AstridSemm** [comment]
Ist schon in der Mache. Siehe hier: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/64

**Comment by xwolfde** [comment]
fixed
