### ISSUE TITLE
Mediendatenbank Suche

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#36]
Möglicherweise nur ein einmaliger Fehler, aber folgendes ist passiert:

Redakteur lädt Foto hoch mit Dateinamen: vorname_nachname.jpg. Da ihm die Rechte zur Verschlagwortung fehlen, kann er keine Kategorie oder Schlagworte vergeben.

Nun sucht er  bzw. auch der Admin in der Medien-Suche nach "nachname" und findet das Foto nicht. Alle anderen Dateien, die "nachname" als Kategorie oder Schlagwort haben, findet Wordpress jedoch.

Durchsucht Wordpress die Dateinamen bei der Suche nicht?

**Comment by xwolfde** [comment]
@rvdforst Ist das Problem noch vorhanden? Kannst du dem nachgehen. Ist leider hier untergangen ;/

**Comment by rvdforst** [comment]
Das Problem tritt nicht mehr auf. Zumindest ist das Problem nicht reproduzierbar. Es ist sehr wahrscheinlich, dass das Problem zu diesem Zeitpunkt mit einer Funktion zusammenhing, die das WP_QUERY-Objekt verändert hat.
