### ISSUE TITLE
Admin-Leiste weg

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#37]
Bei einem Redakteur fehlt auf einer Seite, die er bearbeiten darf, die Admin-Leiste. Die Seite ist genauso eingestellt / aufgebaut wie alle anderen Seiten seines Arbeitskreises, wo die Admin-Leiste vorhanden ist. Ihm fehlt nur auf dieser einen Seite die Admin-Leiste. 

Hat jemand eine Idee, woran das liegen könnte? 

Er verwendet:
Firefox 46.0.1
Windows 7 Enterprises 64-bit SP1
Intel Core i5-3470 CPU @ 3.20 GHz, 8,0GB RAM, Intel HD Graphics

Hier fehlt die Leiste: 
![screenshot](https://cloud.githubusercontent.com/assets/8234890/15924233/58e4ac4c-2e31-11e6-987d-6cbe01fafc68.png)
Hier ist die Leiste da: 
![screenshot_2](https://cloud.githubusercontent.com/assets/8234890/15924236/5b54608a-2e31-11e6-82c8-ac054790049e.png)

**Comment by steffigebel** [comment]
Einfach nochmal Browser schließen und neu anmelden. Passiert manchmal.

Von meinem iPhone gesendet

Am 09.06.2016 um 11:02 schrieb cibsell <notifications@github.com<mailto:notifications@github.com>>:


Bei einem Redakteur fehlt auf einer Seite, die er bearbeiten darf, die Admin-Leiste. Die Seite ist genauso eingestellt / aufgebaut wie alle anderen Seiten seines Arbeitskreises, wo die Admin-Leiste vorhanden ist. Ihm fehlt nur auf dieser einen Seite die Admin-Leiste.

Hat jemand eine Idee, woran das liegen könnte?

Hier fehlt die Leiste:
[screenshot]<https://cloud.githubusercontent.com/assets/8234890/15924233/58e4ac4c-2e31-11e6-987d-6cbe01fafc68.png>
Hier ist die Leiste da:
[screenshot_2]<https://cloud.githubusercontent.com/assets/8234890/15924236/5b54608a-2e31-11e6-82c8-ac054790049e.png>
