### ISSUE TITLE
Farbgebung Accordion-Menü

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#4]
Hallo,

das Accordion-Menü ist mit den aktuellen Farbtönen schwer lesbar. Insbesondere, wenn Überschriften oder Links in dem Textfeld hinterlegt sind, da grüne Schrift auf grünem Hintergrund keinen ausreichenden Kontrast bildet. Wäre es möglich hier die Farben im Textfeld von fau.de zu übernehmen (hellgrau)? Gerne auch im Überschriften-Balken als Texthintergrund ein helleres Grün.

Screenshot:
![accordion-nat](https://cloud.githubusercontent.com/assets/8234890/8650037/0545337a-2970-11e5-813a-a54343041a61.jpg)

**Comment by xwolfde** [comment]
Ist durch neue Version erledigt

**Comment by cibsell** [comment]
Super, sieht viel besser aus! Danke schön.
