### ISSUE TITLE
Portalmenue Mobile Endgeräte

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#5]
Das Portalmenü (nur Textlinks) zeigt in der mobilen Version (Auflösung 320x480) Listenpunkte an, die so wohl nicht sein sollten.

![screenshot-mobil-portalmenue](https://cloud.githubusercontent.com/assets/8234890/8651739/04d6b2b4-297b-11e5-82b5-0067911ae8e0.jpg)

**Comment by steffigebel** [comment]
Nein, das soll so nicht sein. Da bei der Entwicklung damals noch über die externe Agentur "mobile lost" festgestellt werden musste, als wir das Projekt übernahmen, müssen wir das erst noch nachschieben. Hier sind wir noch nicht in der Optimierungsphase ;-) Kommt aber!

**Comment by xwolfde** [comment]
Muss gemacht werden.

**Comment by xwolfde** [comment]
Erster Entwurf ist da. Muss noch für Fakultäten getestet und dann released werden. Ist noch nicht im Git. Kommt.

**Comment by xwolfde** [comment]
Beim nächsten Update drin. Test erfolgt in Kürze zunächst mit FAU-Einrichtungen Theme. Wenn dann alles klappt, kommt das unmittelbar auch auf das Fakultätsheme

**Comment by xwolfde** [comment]
fixed
