### ISSUE TITLE
Das RRZE-Access-Control-Plugin wurde nicht richtig konfiguriert. Die Dateien/Dokumente können nicht geschützt werden. Bitte wenden Sie sich an den Systemadministrator.

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#53]
Fehlermeldung im Dashboard bzw. auf allen Seiten im Backend. Muss ich da etwas machen oder liegt's an euch? :) Der Webauftritt wurde immens verlangsamt dadurch. Habe das Plugin jetzt mal abgeschaltet.

Fehlermeldung:
Das RRZE-Access-Control-Plugin wurde nicht richtig konfiguriert. Die Dateien/Dokumente können nicht geschützt werden. Bitte wenden Sie sich an den Systemadministrator.

**Comment by xwolfde** [comment]
das access control plugin wurde inzwischen umgebaut. Tritt der Fehler noch auf?

**Comment by rvdforst** [comment]
Tatsächlich ist dieses Problem, das durch das Plugin verursacht wurde, bereits gelöst. Daher ist es sicher, das Plugin zu aktivieren.
