### ISSUE TITLE
Reihenfolge unter Auswahl Ansprechpartner

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#6]
Bitte alphabetisch nach Nachnamen sortieren! Wenn in dem Mini-Auswahlkasten mehr als 10 Kontakte stehen, davon noch ein paar mit den Allerweltsnamen Andreas, Julia etc., dann ist es mühsam nach Vornamen sortiert zu suchen. Sortierung nach Nachnamen spart Zeit und ist üblicher (und vermeidet gegebenfalls Frust, wenn man die genauen Vornamen nicht weiß und erst im UnivIS nachsehen muss...).

**Comment by steffigebel** [comment]
Welchen Kasten genau meinen Sie?
Es wird derzeit nach Vornamen-Alphabetisch sortiert. Das können die Programmierer erst dann machen, wenn mal so richtig viel Zeit ist. Alles andere hat derzeit Priorität. Damit ist keine Funktion eingeschränkt ;-)
Bitte um Nachsicht!

Grüße,
Steffi Gebel
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Natfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 5. August 2015 14:08
An: RRZE-Webteam/FAU-Natfak <FAU-Natfak@noreply.github.com<mailto:FAU-Natfak@noreply.github.com>>
Betreff: [FAU-Natfak] Reihenfolge unter Auswahl Ansprechpartner (#6)


Bitte alphabetisch nach Nachnamen sortieren! Wenn in dem Mini-Auswahlkasten mehr als 10 Kontakte stehen, davon noch ein paar mit den Allerweltsnamen Andreas, Julia etc., dann ist es mühsam nach Vornamen sortiert zu suchen. Sortierung nach Nachnamen spart Zeit und ist üblicher (und vermeidet gegebenfalls Frust, wenn man die genauen Vornamen nicht weiß und erst im UnivIS nachsehen muss...).

**Comment by cibsell** [comment]
Generell sollte immer nach Nachnamen sortiert werden! Egal in welchem Kasten und welchem Plugin. 

Im oben genannten Fall ist es der Kasten Ansprechpartner (unter Sidebar). Dort kann man die Kontakte auswählen, die angezeigt werden sollen. Die Auswahlansicht ist nach Vornamen sortiert.

**Comment by steffigebel** [comment]
In der Zukunft wird das auch so sein. War auch so gedacht, hier ist der Grund einfach die Feldbelegung beginnend mit Vornamen. Einige Boxen, wie zum Beispiel die Metabox ist nun nach Nachnamen sortiert. Siehe https://github.com/RRZE-Webteam/fau-person/issues/62#issuecomment-128029488

Grüße,
Steffi Gebel
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Natfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 5. August 2015 16:03
An: RRZE-Webteam/FAU-Natfak <FAU-Natfak@noreply.github.com<mailto:FAU-Natfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Natfak] Reihenfolge unter Auswahl Ansprechpartner (#6)


Generell sollte immer nach Nachnamen sortiert werden! Egal in welchem Kasten und welchem Plugin.

Im oben genannten Fall ist es der Kasten Ansprechpartner (unter Sidebar). Dort kann man die Kontakte auswählen, die angezeigt werden sollen. Die Auswahlansicht ist nach Vornamen sortiert.

**Comment by xwolfde** [comment]
Ist hier alles geklärt oder noch offen? Ansonsten kann der Fall geschlossen werden, oder?

**Comment by cibsell** [comment]
Ist noch offen, im Feld "Auswahl Ansprechpartner" wird immer noch nach Vorname sortiert.

**Comment by xwolfde** [comment]
Also wenn es sich um das Auswahlfeld für die Kontakte in der SIdebar handelt: Dort wird nicht nach Vorname des Kontaktes sortiert, sondern nach dem Eintrag "Titel". Und das ist auch gewollt so.

**Comment by cibsell** [comment]
Um dieses Feld geht es. Es macht keinen Sinn nach "Titel" zu sortieren. Es muss nach Nachname sortiert werden.

**Comment by xwolfde** [comment]
Für mich macht es aber Sinn. Denn den Titel kann man selbst individuell befüllen. Also auch mit den Nachnamen oder nach anderen Eingaben, nach denen man lieber sortieren möchte.
Das wäre nicht so, wenn wir es fest auf Nachname setzen würden.

**Comment by xwolfde** [comment]
Eine Änderung würde bedeuten, dass wir es auch bei FAU, Phil und Med ändern müssen. Dort sind die Leute die es nutzen schon so darin gewohnt und geschult. Weiterhin gibt es aus dem Bereich bereits mehrere andere Websites, die es ebenfalls schon so nutzen.
Von daher ist es für mich momentan keine Option, dies einfach mal so zu ändern. Zumal ihr von der Nat ja noch gar keine Schulung bekommen hattet und das Theme noch nicht so breit nutzt.
