### ISSUE TITLE
Bild lässt sich nicht an gewünschter Stelle einfügen

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#63]
Bei https://geographie.cms.rrze.uni-erlangen.de/ag-boden-baeumler/ hüpft das Bild immer nach unten, auch wenn es mit img class = alignright eingefügt ist. Es soll aber rechts oben zu Beginn des Textes stehen. Das Bild steht aber immer unterhalb der Sidebar. Ist das ein Bug oder ein Feature?

**Comment by AstridSemm** [comment]
Bei mir hüpft nichts. Ist das noch ein issue oder hat sich's gegeben?

**Comment by cibsell** [comment]
Hat sich gegeben, wie es ausieht. Danke.
