### ISSUE TITLE
Accordion klappt nicht auf

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#7]
Das Accordion klappt nicht auf. Keine Ahnung, wieso nicht. Habe alle RRZE-Plugins und das Theme auf dem neuesten Stand, alle anderen Plugins abgeschaltet.

**Comment by xwolfde** [comment]
hast du dazu eine URL auf der Testinstanz?

**Comment by cibsell** [comment]
Nein... Das liegt auf der NAT-Instanz.

**Comment by cibsell** [comment]
Das Accordion geht auf der deutschen Chemie-Webseite, aber nicht auf der englischen Chemie-Webseite. Die englische Seite hat aber genau die gleichen Einstellungen wie die deutsche Seite und auch das gleiche NAT-Theme. Hat das etwas mit der Versionierung zu tun?

**Comment by xwolfde** [comment]
Bitte mal URLs angeben.

**Comment by cibsell** [comment]
http://chem.nat.fau.de/department/ehemalige/, http://chem.nat.fau.de/en/emeriti/

**Comment by xwolfde** [comment]
Die englische Installation ist fehlerhaft: Die Pfade zu den JS-Files funktionieren so nicht.
![bug-chem-nat-en-install](https://cloud.githubusercontent.com/assets/1070669/10068875/69f939d0-62a8-11e5-81f0-b45e91578c41.png)

**Comment by cibsell** [comment]
Ich habe als Test noch eine weitere Seite erstellt und diese über Versionierung/Übersetzung in Workflow verknüpft. Da funktioniert es auch nicht.

**Comment by xwolfde** [comment]
URL?

**Comment by cibsell** [comment]
http://chem.nat.fau.de/eng/ehemalige und http://chem.nat.fau.de/ehemalige

Auf /eng/ ist nur das NAT-Theme und Workflow aktiviert und auch nichts an den Standardeinstellungen verändert.

**Comment by xwolfde** [comment]
Installation des Themes ist noch immer fehlerhaft...
![bug-chem-nat-en-install2](https://cloud.githubusercontent.com/assets/1070669/10075487/4f7df194-62d6-11e5-9e14-41550719753c.png)

**Comment by cibsell** [comment]
Kannst Du mir auch sagen, wo der Fehler liegt? 

Das Theme liegt unter /websource/wp-content/themes/FAU-Natfak-master . Ich habe es über den Wordpress-Installer installiert und Updates per WinSCP hochgeladen...

**Comment by xwolfde** [comment]
Ich *vermute*, du hast bei der WP-Installation auf Directory-Based konfiguriert und dabei irgendein Fehler gemacht. Jedenfalls -und das siehst du ja, wenn du dir wie ich den Developer anschaust- wird versucht die Themedateien in einem Ordern /eng/en/wp-content/   zu finden, den es natürlich nicht gibt.

Du könntest in deiner Netzwerkadmin-Oberfläche schauen, ob da irgendwelche Pfade zu der SIte falsch sind. Ansonst würde ich  *versuchen* als Workaround einfach einen Softlink  von /eng/en/wp-content   auf /wp-content   zu legen. Ob das eine Lösung wäre kann ich aber so nicht sagen.

**Comment by cibsell** [comment]
Ich habe Wordpress damals so installiert, wie ihr es mir gesagt habt...

**Comment by xwolfde** [comment]
Wir haben niemals etwas zu einer Multisite-Installation gesagt. Und du hast uns damals auch nicht gesagt, dass du dort so einen Einsatz planst.
Wir hingegen sagen seit Jahren (und das ist auch nachlesbar in den öffentlichen FAQs!), dass für Mehrsprachige Webauftritte jeweils auch eigene Domains verwendet werden sollten. Wenn du dich an unseren Empfehlungen nicht halten willst, kannst du das tun, aber auf eigenes Risiko.

**Comment by cibsell** [comment]
Das stimmt doch so überhaupt nicht! 

Es war von vornherein klar - und das habe ich auch entsprechend euch kommuniziert -, dass der Einsatz einer mehrsprachigen Webseite geplant ist. Dafür habt ihr mir diese Vorgehensweise empfohlen. 

Im übrigen: wenn das oben genannte Problem bei zwei voneinander unabhängigen Instanzen besteht, dann ist es wohl eher ein Problem vom Theme oder Plugin und nicht von der Installation.

**Comment by xwolfde** [comment]
Dann liegt hier offensichtlich ein Missverständnis vor darüber was wir gesagt haben, wie das gemeint war und darüber wie das verstanden wurde.
Für den Einsatz von mehrsprachigen Sites empfehlen wir seit Jahren auch eigenständige Domains. Daran hat sich nichts geändert. Nur weil WP die Möglichkeit bietet, Multisites auch directory-based zu machen anstelle domain-based und wir WP nun mal empfehlen, heißt es nicht, daß wir deswegen von unseren langjährigen Politik abweichen.
Oder willst du uns als nächstes auch verantwortlich dafür machen, dass jemand bunte blinkende Laufschrift auf seiner Website nutzt, nur weil HTML+CSS das ermögllicht, aber wir mit HTML+CSS einsetzen?

Du wolltest es selbst installieren weil du unsere Plattform die seit Januar bereitstand nicht wolltest, also ist es auch dein eigener Job, es hinzukriegen. Wenn was nicht funktioniert, finde bitte erstmal selbst raus woran es liegen könnte und versuche selbst eine Lösung zu finden.
