### ISSUE TITLE
Template Department-Startseite

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#8]
Wo muss ich welche Einstellungen vornehmen, damit mir das Template Department-Startseite angezeigt wird?

**Comment by xwolfde** [comment]
Das Template "Startseite" ist das für Lehrstühle und unterhalb der Fakultät befindlichen Einrichtungen.
Das Template "Startseite Fakultät" ist das für die Startseite einer Fakultät.

(Die Bezeichnungen wurden umgedreht, da die meisten dann Lehrstühle sein werden, die dann eben nur "Startseite" verwenden)
Was meinst du mit Department-Startseite?

**Comment by cibsell** [comment]
Danke! Ich bin davon ausgegangen, dass "Startseite" die FAU-Startseite anzeigt... Jetzt funktioniert es mit dem Lehrstuhl/Departments-Template.
