### ISSUE TITLE
Titel in Lehrstuhl-Template

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Natfak#9]
Im Lehrstuhl-Startseiten-Template ist nach dem Titel der Webseite ein kleines grünes Kästchen.

![screenshot](https://cloud.githubusercontent.com/assets/8234890/9878857/1e780b60-5bc5-11e5-86d1-36176a96895b.jpg)

**Comment by xwolfde** [comment]
Haste mal ne URL?

**Comment by xwolfde** [comment]
Ah, schon gefunden. Wird beim nöchsten Update korrigiert.  - Gleich
